"use client";

import { useParams, useRouter } from "next/navigation";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import Link from "next/link";
import {
  Earnings,
  type EarningsQuarter,
  type EstimateRevision,
  type RecommendationMix,
} from "@/lib/api";

// ──────────────────────────────────────────────────────────────────────
// Earnings viewer — latest reported quarter, 4-quarter history, forward
// analyst-estimate revisions, recommendation mix, and the AI-generated
// summary if one exists.
//
// "Queue summary" drops a run_queue item with mode=earnings_summary;
// Claude Desktop's tradingagents-analyze skill picks it up, generates
// the bullet + structured comparison, POSTs back to
// /earnings/{ticker}/summary. The page polls every 30s while pending.
// ──────────────────────────────────────────────────────────────────────

function fmtUsd(n: number | null): string {
  if (n === null || n === undefined) return "—";
  const abs = Math.abs(n);
  if (abs >= 1_000_000_000) return `$${(n / 1_000_000_000).toFixed(2)}B`;
  if (abs >= 1_000_000) return `$${(n / 1_000_000).toFixed(1)}M`;
  if (abs >= 1_000) return `$${(n / 1_000).toFixed(1)}K`;
  return `$${n.toFixed(2)}`;
}

function fmtEps(n: number | null): string {
  if (n === null || n === undefined) return "—";
  return n.toFixed(2);
}

function fmtPct(n: number | null, withSign = true): string {
  if (n === null || n === undefined) return "—";
  const sign = withSign && n > 0 ? "+" : "";
  return `${sign}${n.toFixed(2)}%`;
}

function surpriseTone(p: number | null): string {
  if (p === null || p === undefined) return "text-muted";
  if (p > 0) return "text-success";
  if (p < 0) return "text-danger";
  return "text-muted";
}

function directionTone(d: string | null): string {
  if (d === "up") return "text-success";
  if (d === "down") return "text-danger";
  return "text-muted";
}

function directionArrow(d: string | null): string {
  if (d === "up") return "↑";
  if (d === "down") return "↓";
  if (d === "flat") return "—";
  return "";
}

const HORIZON_LABEL: Record<EstimateRevision["horizon"], string> = {
  current_quarter: "Current quarter",
  next_quarter: "Next quarter",
  current_year: "Current year",
  next_year: "Next year",
};

export default function EarningsPage() {
  const params = useParams<{ ticker: string }>();
  const ticker = (params.ticker || "").toUpperCase();
  const qc = useQueryClient();

  const q = useQuery({
    queryKey: ["earnings", ticker],
    queryFn: () => Earnings.get(ticker),
    enabled: !!ticker,
    // While a summary is pending, poll more frequently to pick up the
    // skill's POST-back. Otherwise refresh once a minute.
    refetchInterval: (q) => (q.state.data?.summary_pending ? 30_000 : 60_000),
    refetchOnWindowFocus: false,
  });

  const queueSummary = useMutation({
    mutationFn: () => Earnings.queueSummary(ticker),
    onSuccess: () => qc.invalidateQueries({ queryKey: ["earnings", ticker] }),
  });

  if (q.isLoading) {
    return <div className="text-muted">Loading…</div>;
  }
  if (!q.data) {
    return <div className="text-danger">No data for {ticker}.</div>;
  }
  const d = q.data;

  return (
    <div className="space-y-6">
      <header>
        <div className="flex items-baseline gap-3 flex-wrap">
          <h1 className="text-2xl font-bold">{d.ticker} earnings</h1>
          {d.next_earnings_date && (
            <span className="text-sm text-muted">
              Next earnings: <strong>{d.next_earnings_date}</strong>
              {d.days_until_next !== null && (
                <> ({d.days_until_next > 0 ? `in ${d.days_until_next}d` : `${-d.days_until_next}d ago`})</>
              )}
            </span>
          )}
        </div>
        <p className="text-muted text-sm mt-1">
          Latest reported quarter + analyst estimate revisions + recommendation
          mix from yfinance. The plain-English summary is generated by Claude
          Desktop via the run queue — click &quot;Request AI summary&quot; to
          drop a request.
        </p>
      </header>

      {/* ─── Latest quarter card ─── */}
      {d.latest_quarter && <LatestQuarterCard q={d.latest_quarter} />}

      {/* ─── AI summary panel ─── */}
      <SummaryPanel
        ticker={d.ticker}
        summary={d.summary}
        pending={d.summary_pending}
        onQueue={() => queueSummary.mutate()}
        queuing={queueSummary.isPending}
        latestQuarterDate={d.latest_quarter?.report_date ?? null}
      />

      {/* ─── Revisions ─── */}
      {d.revisions.length > 0 && <RevisionsTable revisions={d.revisions} />}

      {/* ─── History ─── */}
      {d.history.length > 0 && <HistoryTable history={d.history} />}

      {/* ─── Analyst recs ─── */}
      {d.recommendations.length > 0 && <RecsTable recs={d.recommendations} />}

      <div className="card text-xs text-muted">
        Data: yfinance. EPS values are diluted-as-reported. Surprise % is{" "}
        (actual − estimate) / estimate × 100. Revision direction flags up/down
        when the current estimate has moved &gt;1% vs 30 days ago.
      </div>
    </div>
  );
}

// ─── Latest quarter card ────────────────────────────────────────────

function LatestQuarterCard({ q }: { q: EarningsQuarter }) {
  return (
    <div className="card">
      <div className="text-xs uppercase text-muted">Latest reported</div>
      <div className="text-lg font-semibold">{q.report_date}</div>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-3">
        <div>
          <div className="text-xs text-muted">EPS actual</div>
          <div className="text-xl font-bold">{fmtEps(q.eps_actual)}</div>
        </div>
        <div>
          <div className="text-xs text-muted">EPS estimate</div>
          <div className="text-xl text-muted">{fmtEps(q.eps_estimate)}</div>
        </div>
        <div>
          <div className="text-xs text-muted">Surprise</div>
          <div className={`text-xl font-bold ${surpriseTone(q.eps_surprise_pct)}`}>
            {fmtPct(q.eps_surprise_pct)}
          </div>
        </div>
        <div>
          <div className="text-xs text-muted">Revenue</div>
          <div className="text-xl font-bold">{fmtUsd(q.revenue_actual)}</div>
          {q.revenue_estimate && (
            <div className="text-xs text-muted">
              est. {fmtUsd(q.revenue_estimate)}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// ─── AI summary panel ───────────────────────────────────────────────

function SummaryPanel({
  ticker,
  summary,
  pending,
  onQueue,
  queuing,
  latestQuarterDate,
}: {
  ticker: string;
  summary: ReturnType<typeof Earnings.get> extends Promise<infer T>
    ? T extends { summary: infer S } ? S : null
    : null;
  pending: boolean;
  onQueue: () => void;
  queuing: boolean;
  latestQuarterDate: string | null;
}) {
  return (
    <div className="card">
      <div className="flex items-baseline gap-3 flex-wrap mb-2">
        <h2 className="text-lg font-semibold">Plain-English summary</h2>
        {summary && (
          <span className="text-xs text-muted">
            for {summary.report_date} · {summary.status} · via {summary.source}
          </span>
        )}
        <div className="ml-auto flex gap-2">
          <button
            className="btn text-xs"
            onClick={onQueue}
            disabled={queuing || pending}
            title={
              pending
                ? "An earnings_summary queue item is already pending"
                : "Drop a queue item that Claude Desktop will pick up"
            }
          >
            {pending
              ? "⏳ Pending in queue…"
              : queuing
                ? "Queueing…"
                : summary
                  ? "↻ Re-queue summary"
                  : "🤖 Request AI summary"}
          </button>
          <Link href="/queue" className="btn text-xs">
            View queue ↗
          </Link>
        </div>
      </div>

      {summary ? (
        <>
          {summary.bullets_md ? (
            <div className="text-sm">
              <Markdown>{summary.bullets_md}</Markdown>
            </div>
          ) : pending ? (
            <div className="text-sm text-muted">
              Queued for {summary.report_date}. Page polls every 30s; the
              summary will appear here when Claude Desktop has processed the
              queue item. Typical turnaround: a few minutes after the next
              skill run.
            </div>
          ) : (
            <div className="text-sm text-muted">
              Summary row exists but no bullets on file — odd state.
            </div>
          )}
          {summary.structured_json && (
            <details className="mt-3">
              <summary className="cursor-pointer text-xs text-muted">
                Structured comparison data
              </summary>
              <pre className="text-xs bg-surface p-3 rounded mt-2 overflow-x-auto">
                {JSON.stringify(summary.structured_json, null, 2)}
              </pre>
            </details>
          )}
        </>
      ) : (
        <div className="text-sm text-muted">
          No summary on file for {ticker}. Click <strong>Request AI summary</strong>{" "}
          to queue one for{" "}
          {latestQuarterDate ? `the ${latestQuarterDate} call` : "the latest call"}.
          The skill will fetch the press release, generate a plain-English
          summary + structured comparison, and POST it back here.
        </div>
      )}
    </div>
  );
}

// ─── Revisions ──────────────────────────────────────────────────────

function RevisionsTable({ revisions }: { revisions: EstimateRevision[] }) {
  return (
    <section>
      <h2 className="text-lg font-semibold mb-2">Analyst EPS estimate revisions</h2>
      <p className="text-xs text-muted mb-3">
        Current consensus EPS estimate per horizon, plus the count of
        analysts who revised <span className="text-success">up</span> vs{" "}
        <span className="text-danger">down</span> in the last 7 and 30 days.
        Net 30-day count is the strongest near-term signal academic research
        identifies — when net is positive and growing, the stock tends to
        drift up in the following weeks.
      </p>
      <div className="card overflow-x-auto">
        <table className="w-full text-sm">
          <thead className="text-left text-xs uppercase text-muted">
            <tr>
              <th className="py-2">Horizon</th>
              <th className="text-right">EPS est</th>
              <th className="text-right">Range</th>
              <th className="text-right">Analysts</th>
              <th className="text-right">Growth</th>
              <th className="text-right text-success">↑7d</th>
              <th className="text-right text-danger">↓7d</th>
              <th className="text-right text-success">↑30d</th>
              <th className="text-right text-danger">↓30d</th>
              <th className="text-right">Net 30d</th>
              <th>Dir</th>
            </tr>
          </thead>
          <tbody>
            {revisions.map((r) => (
              <tr key={r.horizon} className="border-t border-border">
                <td className="py-2 font-semibold">{HORIZON_LABEL[r.horizon]}</td>
                <td className="text-right tabular-nums">{fmtEps(r.current_estimate)}</td>
                <td className="text-right tabular-nums text-muted text-xs">
                  {fmtEps(r.low_estimate)} – {fmtEps(r.high_estimate)}
                </td>
                <td className="text-right tabular-nums text-muted">
                  {r.analyst_count ?? "—"}
                </td>
                <td className={`text-right tabular-nums ${(r.growth_pct ?? 0) > 0 ? "text-success" : (r.growth_pct ?? 0) < 0 ? "text-danger" : "text-muted"}`}>
                  {fmtPct(r.growth_pct)}
                </td>
                <td className="text-right tabular-nums text-success">
                  {r.up_last_7d ?? "—"}
                </td>
                <td className="text-right tabular-nums text-danger">
                  {r.down_last_7d ?? "—"}
                </td>
                <td className="text-right tabular-nums text-success">
                  {r.up_last_30d ?? "—"}
                </td>
                <td className="text-right tabular-nums text-danger">
                  {r.down_last_30d ?? "—"}
                </td>
                <td className={`text-right tabular-nums font-semibold ${(r.net_30d ?? 0) > 0 ? "text-success" : (r.net_30d ?? 0) < 0 ? "text-danger" : "text-muted"}`}>
                  {r.net_30d === null ? "—" : (r.net_30d > 0 ? `+${r.net_30d}` : r.net_30d)}
                </td>
                <td className={`text-lg font-bold ${directionTone(r.direction)}`}>
                  {directionArrow(r.direction)}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}

// ─── History ────────────────────────────────────────────────────────

function HistoryTable({ history }: { history: EarningsQuarter[] }) {
  return (
    <section>
      <h2 className="text-lg font-semibold mb-2">Recent quarters</h2>
      <div className="card overflow-x-auto">
        <table className="w-full text-sm">
          <thead className="text-left text-xs uppercase text-muted">
            <tr>
              <th className="py-2">Quarter ended</th>
              <th className="text-right">EPS actual</th>
              <th className="text-right">Estimate</th>
              <th className="text-right">Surprise</th>
              <th className="text-right">Revenue</th>
            </tr>
          </thead>
          <tbody>
            {history.map((h) => (
              <tr key={h.report_date} className="border-t border-border">
                <td className="py-2">{h.report_date}</td>
                <td className="text-right tabular-nums">{fmtEps(h.eps_actual)}</td>
                <td className="text-right tabular-nums text-muted">{fmtEps(h.eps_estimate)}</td>
                <td className={`text-right tabular-nums ${surpriseTone(h.eps_surprise_pct)}`}>
                  {fmtPct(h.eps_surprise_pct)}
                </td>
                <td className="text-right tabular-nums">{fmtUsd(h.revenue_actual)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </section>
  );
}

// ─── Analyst rec mix ────────────────────────────────────────────────

function RecsTable({ recs }: { recs: RecommendationMix[] }) {
  return (
    <section>
      <h2 className="text-lg font-semibold mb-2">Analyst rating mix</h2>
      <div className="card overflow-x-auto">
        <table className="w-full text-sm">
          <thead className="text-left text-xs uppercase text-muted">
            <tr>
              <th className="py-2">Period</th>
              <th className="text-right text-success">Strong buy</th>
              <th className="text-right text-success">Buy</th>
              <th className="text-right text-muted">Hold</th>
              <th className="text-right text-danger">Sell</th>
              <th className="text-right text-danger">Strong sell</th>
              <th className="text-right">Total</th>
            </tr>
          </thead>
          <tbody>
            {recs.map((r) => {
              const total =
                (r.strong_buy ?? 0) +
                (r.buy ?? 0) +
                (r.hold ?? 0) +
                (r.sell ?? 0) +
                (r.strong_sell ?? 0);
              return (
                <tr key={r.period} className="border-t border-border">
                  <td className="py-2 text-xs text-muted">{r.period}</td>
                  <td className="text-right tabular-nums">{r.strong_buy ?? "—"}</td>
                  <td className="text-right tabular-nums">{r.buy ?? "—"}</td>
                  <td className="text-right tabular-nums">{r.hold ?? "—"}</td>
                  <td className="text-right tabular-nums">{r.sell ?? "—"}</td>
                  <td className="text-right tabular-nums">{r.strong_sell ?? "—"}</td>
                  <td className="text-right tabular-nums font-semibold">{total}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </section>
  );
}
