# TradingAgents — Windows Scheduled Task installer (silent / no console window)
#
# Sets up a Windows Scheduled Task that runs the `claude` CLI in headless
# mode every 30 minutes to drain the run-queue. The CLI uses your Claude
# Max subscription (NOT API tokens), so this is free as long as you're
# logged in.
#
# Silence: Windows Scheduled Tasks normally pop up a console window when
# the action is a console program (claude.exe). To make this truly silent
# we install a VBScript wrapper at %LOCALAPPDATA%\TradingAgents\drain.vbs
# and point the task at wscript.exe + that wrapper. WScript has no
# console of its own and runs cmd hidden, so the user sees nothing while
# the drain runs in the background.
#
# Output goes to %LOCALAPPDATA%\TradingAgents\drain.log (rolling) so you
# can still debug if a drain fails.
#
# Requires:
#   - Claude Code installed (`claude --version` should print something)
#   - You're logged into Claude Code under your Max account
#   - Network access to the NAS api at http://192.168.2.34:8001
#
# Usage (run from PowerShell — admin not required):
#   .\scripts\install-windows-drain-task.ps1
#
# Uninstall:
#   Unregister-ScheduledTask -TaskName "TradingAgents Drain Queue" -Confirm:$false
#   Remove-Item "$env:LOCALAPPDATA\TradingAgents\drain.vbs" -ErrorAction SilentlyContinue
#   Remove-Item "$env:LOCALAPPDATA\TradingAgents\drain.log" -ErrorAction SilentlyContinue

$ErrorActionPreference = "Stop"

$TaskName = "TradingAgents Drain Queue"
$ApiUrl   = "http://192.168.2.34:8001"

# The prompt invokes the tradingagents-analyze skill via its "process the
# queue" trigger. The skill walks /run-queue/pending and routes each item
# by mode. See ~/.claude/skills/tradingagents-analyze/SKILL.md for the
# full dispatch table.
$Prompt = "Process the queue at $ApiUrl/run-queue/pending. Drain everything."

# Find the claude CLI. Tries the default install path, then PATH.
$ClaudeExe = $null
$ClaudeCandidates = @(
    "$env:LOCALAPPDATA\Programs\claude\claude.exe",
    "$env:APPDATA\npm\claude.cmd",
    "$env:LOCALAPPDATA\Anthropic\Claude\claude.exe"
)
foreach ($c in $ClaudeCandidates) {
    if (Test-Path $c) { $ClaudeExe = $c; break }
}
if (-not $ClaudeExe) {
    $found = Get-Command claude -ErrorAction SilentlyContinue
    if ($found) { $ClaudeExe = $found.Source }
}
if (-not $ClaudeExe) {
    Write-Host "ERROR: Could not find claude CLI. Install Claude Code first." -ForegroundColor Red
    Write-Host "Then re-run this script."
    exit 1
}
Write-Host "Found claude CLI at: $ClaudeExe" -ForegroundColor Green

# ── Write the VBScript wrapper. wscript.exe runs this with NO window of
# its own, then sh.Run("cmd", 0, ...) hides cmd, which hides claude.
# The 0 in the third arg = SW_HIDE; True at the end = wait for completion
# so the task's LastRunResult reflects claude's actual exit code.
$VbsDir = "$env:LOCALAPPDATA\TradingAgents"
$VbsPath = Join-Path $VbsDir "drain.vbs"
$LogPath = Join-Path $VbsDir "drain.log"
if (-not (Test-Path $VbsDir)) {
    New-Item -ItemType Directory -Path $VbsDir -Force | Out-Null
}

# Build the VBS content. Escape quotes inside the cmd string for VB syntax
# (VB uses "" for embedded quotes).
$EscapedClaudeExe = $ClaudeExe.Replace('"', '""')
$EscapedPrompt = $Prompt.Replace('"', '""')
$VbsContent = @"
' TradingAgents queue drainer — silent wrapper.
' Auto-generated by install-windows-drain-task.ps1. Do not edit by hand;
' re-run the installer to update.
'
' wscript.exe runs this WITHOUT a console window, then sh.Run launches
' cmd with the SW_HIDE flag (third arg = 0). The user sees nothing.
' Output redirected to drain.log for post-hoc debugging.
Set sh = CreateObject("WScript.Shell")
Set fso = CreateObject("Scripting.FileSystemObject")

' Rotate the log if it grew past 1 MB so we don't fill the disk over
' months of drains. Keeps drain.log.old as last-rotation backup.
logPath = "$($LogPath.Replace('\','\\').Replace('"','""'))"
If fso.FileExists(logPath) Then
    If fso.GetFile(logPath).Size > 1048576 Then
        oldPath = logPath & ".old"
        If fso.FileExists(oldPath) Then fso.DeleteFile oldPath
        fso.MoveFile logPath, oldPath
    End If
End If

' Timestamp the entry so the log is easy to scan.
ts = Now()
sh.Run "cmd /c echo. >> """ & logPath & """ && echo [" & ts & "] start >> """ & logPath & """ && """ & "$EscapedClaudeExe" & """ -p """ & "$EscapedPrompt" & """ >> """ & logPath & """ 2>&1 && echo [" & Now() & "] done >> """ & logPath & """", 0, True
"@

Set-Content -Path $VbsPath -Value $VbsContent -Encoding ASCII
Write-Host "Wrote silent wrapper to: $VbsPath" -ForegroundColor Green
Write-Host "Drain output will land in: $LogPath"

# ── Build the scheduled task pointing at wscript + the wrapper.
$WScriptExe = "$env:SystemRoot\System32\wscript.exe"
$Action = New-ScheduledTaskAction `
    -Execute $WScriptExe `
    -Argument "`"$VbsPath`""

# Repeat every 30 min, indefinitely, starting at the next half-hour.
$Now = Get-Date
$StartAt = $Now.AddMinutes(2)
$Trigger = New-ScheduledTaskTrigger `
    -Once `
    -At $StartAt `
    -RepetitionInterval (New-TimeSpan -Minutes 30)

$Settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -RunOnlyIfNetworkAvailable `
    -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Hours 2)
# 2-hour limit: a single drain may need to process 6+ heavy `analyze`
# items at 3-5 min each. MultipleInstances=IgnoreNew prevents
# overlapping runs, so a long drain just skips the next 30-min tick.

$Principal = New-ScheduledTaskPrincipal `
    -UserId "$env:USERDOMAIN\$env:USERNAME" `
    -LogonType Interactive `
    -RunLevel Limited

# Register (replace if exists)
Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue | ForEach-Object {
    Write-Host "Removing existing task..." -ForegroundColor Yellow
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $Action `
    -Trigger $Trigger `
    -Settings $Settings `
    -Principal $Principal `
    -Description "Drains the TradingAgents queue via 'claude -p' every 30 min (silent VBScript wrapper, no console window). Output → $LogPath"

Write-Host ""
Write-Host "Installed scheduled task '$TaskName'." -ForegroundColor Green
Write-Host "First run: $StartAt" -ForegroundColor Green
Write-Host "Interval:  every 30 minutes (silent — no console window will appear)"
Write-Host ""
Write-Host "To verify it works right now, run:"
Write-Host "  Start-ScheduledTask -TaskName '$TaskName'" -ForegroundColor Cyan
Write-Host ""
Write-Host "To watch the drain output live as it runs:"
Write-Host "  Get-Content '$LogPath' -Wait -Tail 50" -ForegroundColor Cyan
Write-Host ""
Write-Host "To check task status:"
Write-Host "  Get-ScheduledTaskInfo -TaskName '$TaskName'"
Write-Host ""
Write-Host "To uninstall:"
Write-Host "  Unregister-ScheduledTask -TaskName '$TaskName' -Confirm:`$false"
Write-Host "  Remove-Item '$VbsDir' -Recurse -ErrorAction SilentlyContinue"
